### ISSUE TITLE
Dart 1.21.0: unable to resolve asset ID for "dart:core"

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/reflectable#91]
Upgrading to Dart **1.21.0** is causing the transformer to fail.

**OS:** MacOS 10.12.1

```
[Error from Reflectable on revolution|web/index.bootstrap.initialize.dart]:
Unable to resolve asset ID for "dart:core"
Build error:
Transform Reflectable on revolution|web/index.bootstrap.initialize.dart threw error: Cannot compute LIBRARY_ELEMENT for Instance of 'AssetBasedSource'
Caused by Could not resolve "dart:core": SDK incorrectly configured
#0      ParseDartTask.internalPerform (package:analyzer/src/task/dart.dart:4178)
#1      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:338)
#2      AnalysisTask.perform (package:analyzer/task/model.dart:238)
#3      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#4      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109)
#5      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:718)
#6      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:691)
#7      ResolverImpl._performResolve.<anonymous closure>.<anonymous closure> (package:code_transformers/src/resolver_impl.dart:153)
#8      MappedListIterable.elementAt (dart:_internal/iterable.dart:416)
#9      ListIterable.toList (dart:_internal/iterable.dart:222)
#10     ResolverImpl._performResolve.<anonymous closure> (package:code_transformers/src/resolver_impl.dart:154)
#11     _RootZone.runUnary (dart:async/zone.dart:1404)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#13     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#14     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#15     _Future._completeWithValue (dart:async/future_impl.dart:477)
#16     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

My project uses `polymer-dart` and `reflectable 1.0.1`.  This error does not occur in Dart 1.20.x

**Comment by jakemac53** [comment]
cc @bwilkerson

**Comment by johnpryan** [comment]
Just to give an update: I downgraded to dart `1.20.1` and the issue is still occuring.  Investigating...

**Comment by johnpryan** [comment]
This is a standard error resulting from setting the `DART_SDK` environment variable to an invalid path, not an issue with `reflectable` or dart `1.21.0`
